# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(503, 479)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 60, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 170, 111, 16))
        self.label_4.setObjectName("label_4")
        self.id = QtWidgets.QPlainTextEdit(Form)
        self.id.setGeometry(QtCore.QRect(160, 60, 261, 31))
        self.id.setObjectName("id")
        self.name = QtWidgets.QPlainTextEdit(Form)
        self.name.setGeometry(QtCore.QRect(160, 110, 261, 31))
        self.name.setObjectName("name")
        self.roasting = QtWidgets.QPlainTextEdit(Form)
        self.roasting.setGeometry(QtCore.QRect(160, 160, 261, 31))
        self.roasting.setObjectName("roasting")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(160, 210, 251, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 400, 201, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 111, 16))
        self.label_5.setObjectName("label_5")
        self.description = QtWidgets.QPlainTextEdit(Form)
        self.description.setGeometry(QtCore.QRect(160, 250, 261, 31))
        self.description.setObjectName("description")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 310, 111, 16))
        self.label_6.setObjectName("label_6")
        self.price = QtWidgets.QPlainTextEdit(Form)
        self.price.setGeometry(QtCore.QRect(160, 300, 261, 31))
        self.price.setObjectName("price")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(50, 360, 111, 16))
        self.label_7.setObjectName("label_7")
        self.volume = QtWidgets.QPlainTextEdit(Form)
        self.volume.setGeometry(QtCore.QRect(160, 350, 261, 31))
        self.volume.setObjectName("volume")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Название сорта"))
        self.label_3.setText(_translate("Form", "Форма"))
        self.label_4.setText(_translate("Form", "Степень обжарки"))
        self.comboBox.setItemText(0, _translate("Form", "Молотый"))
        self.comboBox.setItemText(1, _translate("Form", "В зёрнах"))
        self.pushButton.setText(_translate("Form", "Добавить/изменить"))
        self.label_5.setText(_translate("Form", " Описание вкуса"))
        self.label_6.setText(_translate("Form", "Цена"))
        self.label_7.setText(_translate("Form", "Объем упаковки"))
